group1/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path(r'', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'index', views.index, name='index'),
    path(r'about', views.about, name='about'),
    path(r'<int:top_no>', views.detail, name='detail'),
    path(r'courses', views.courses, name='courses'),
    path(r'place_order', views.place_order, name='place_order'),
    path(r'courses/<int:cour_id>', views.coursedetail, name='coursedetail'),
    path(r'login', views.user_login, name='login'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'myaccount', views.myaccount, name='myaccount'),
    path(r'myorders', views.myorders, name='myorders'),
    path(r'register', views.register, name='register'),
    path(r'password_reset', views.password_reset, name='password_reset')

]

myapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=50, null=False, blank=False, default='Category1')
    length = models.IntegerField( default=1)

    def __str__(self):
        return self.name + " , " + self.category


# project - task 9 - adding validator for price of course
def validate_price(value):
    if value < 50 or value > 500:
        raise ValidationError('Price should be between 50 and 500')


class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_price])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def __str__(self):
        return self.name

    def discount(self):
        self.price = self.price * 90 / 100
        return self.price


class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
                    ('CG', 'Calgary'),
                    ('MR', 'Montreal'),
                    ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)

    def __str__(self):
        return self.last_name + " " + self.first_name


class Order(models.Model):
    VALID_CHOICES = [
        (0, 'Cancelled'),
        (1, 'Confirmed'),
    ]
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    levels = models.PositiveIntegerField(default=1)
    order_status = models.IntegerField(choices=VALID_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)

    def total_cost(self):
        # returns total cost of all courses in order;
        return sum([course_item.price for course_item in self.course.all()])

    def __str__(self):
        return "order no:" + str(self.id) + " course: " + str(self.course.name) + " Student ID: " + str(self.student)


class Image(models.Model):
    image = models.ImageField(upload_to='images/')

class PasswordReset(models.Model):
    username = models.CharField(max_length=200)

    def __str__(self):
        return self.username

myapp/forms.py
from django import forms
from myapp.models import Order, Student, Course, Image, PasswordReset,Topic


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image',)

class PasswordResetForm(forms.ModelForm):
    class Meta:
        model = PasswordReset
        fields = ('username',)

class InterestForm(forms.Form):
    CHOICES = [(0, 'No'),
               (1, 'Yes')]
    interested = forms.CharField(label='Interested', widget=forms.RadioSelect(choices=CHOICES))
    levels = forms.IntegerField(min_value=1, initial=1)
    comments = forms.CharField(label='Additional Comments', widget=forms.Textarea, required=False)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ( 'course', 'levels')
        # widgets = {
        #     'order_date': forms.SelectDateWidget
        # }


class StudentRegistrationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('school', 'city', 'interested_in')
    CITY_CHOICES = [('WS', 'Windsor'),
                    ('CG', 'Calgary'),
                    ('MR', 'Montreal'),
                    ('VC', 'Vancouver')]
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    email = forms.CharField(label='Email', max_length=100)
    school = forms.CharField(label='School', max_length=50, required=False)
    city = forms.CharField(label='City', widget=forms.RadioSelect(choices=CITY_CHOICES), initial='WS')
    interested_in = forms.ModelMultipleChoiceField(queryset=Topic.objects.all(), widget=forms.CheckboxSelectMultiple)

myapp/views.py
from django.core.exceptions import ObjectDoesNotExist
import datetime
import json
from django.utils import timezone
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings

from .models import Topic, Course, Student, Order
from django.shortcuts import get_object_or_404
from myapp.forms import OrderForm, InterestForm, ImageForm, PasswordResetForm, StudentRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import hashers
import random, string


# Create your views here.
def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    browserClose = request.session.get_expire_at_browser_close()
    if 'last_login' in request.session:
        last_login = request.session['last_login']
    else:
        last_login = 0
    return render(request, 'myapp/index.html',
                  {'top_list': top_list, 'last_login': last_login, 'browserCLose': browserClose})


def index_old(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    response = HttpResponse()
    heading1 = '<p>' + 'List of topics: ' + '</p>'
    response.write(heading1)
    for topic in top_list:
        para = '<p>' + str(topic.id) + ': ' + str(topic) + '</p>'
        response.write(para)
        course_list = Course.objects.filter(topic=topic).order_by('-price')[:5]
        for course in course_list:
            course_para = '&nbsp;&nbsp;&nbsp;<span>' + str(course.name) + ': ' + str(course.price)
            if course.for_everyone is True:
                course_para += '&nbsp;&nbsp; This course is for everyone!'
            else:
                course_para += '&nbsp;&nbsp; This course is not for everyone!'
            course_para += '</span><br>'
            response.write(course_para)
    return response


def about(request):
    response = HttpResponse()
    count = 1
    about_visits = request.COOKIES.get('about_visits')
    print(about_visits)
    if about_visits:
        count = int(about_visits) + 1
    else:
        count = 1

    response = render(request, 'myapp/about.html', {'count': count})
    response.set_cookie(key='about_visits', value=count, max_age=300)
    return response


def about_old(request):
    response = HttpResponse()
    response.write("This is an E-learning Website! Search our Topics to find all available Courses.")
    return response


def detail(request, top_no):
    response = HttpResponse()
    topic = Topic.objects.filter(id=top_no).first()
    return render(request, 'myapp/detail.html', {'topic': topic})


def detail_old(request, top_no):
    topic = Topic.objects.filter(id=top_no).values()
    if not topic:
        data = get_object_or_404(topic)
    else:
        response = HttpResponse()
        para = '<p>Detail for Topic <br>ID: ' + str(topic[0].get('id')) + '<br> Name: <b>' + str(
            topic[0].get('name')) + '</b><br>Category: <b>' + str(topic[0].get('category')) + '</b></p>'
        course_list = Course.objects.filter(topic=topic[0].get('id'))
        print(course_list)
        heading = '<p>List of course for that topic are as below</p>'
        data = para + heading
        for course in course_list:
            data += '<li>' + str(course) + '</li>'
    response.write(data)
    return response


def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})


def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.student_id = request.user.id
            if order.levels <= order.course.stages:
                order.order_date = datetime.datetime.now()
                order.save()
                cour_id = int(form['course'].value())
                course = Course.objects.get(id=cour_id)
                if course.price > 150:
                    course.discount()
                    course.save()

                msg = 'Your order has been placed successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        if (request.user.is_authenticated):
            form = OrderForm()
        else:
            form = None
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist})


def coursedetail(request, cour_id):
    course = Course.objects.get(id=cour_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            interest = form.cleaned_data['interested']
            print(interest)
            if int(interest) == 1:
                course.interested += 1
                course.save()
            return redirect('myapp:index')
    else:
        form = InterestForm()
    return render(request, 'myapp/coursedetail.html', {'form': form, 'course': course})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
        request.session.set_test_cookie()
        now = datetime.datetime.now()
        json_str = json.dumps(now, default=str)
        request.session['last_login'] = json_str
        request.session.set_expiry(3600);
        user = authenticate(username=username, password=password)
        print(user)
        if user:
            if user.is_active:
                login(request, user)
                print('authenticated')
                return HttpResponseRedirect(reverse('myapp:myaccount'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


def user_logout(request):
    logout(request)
    # del request.session['last_login']
    return HttpResponseRedirect(reverse(('myapp:login')))


# @login_required
def myaccount(request):
    if request.user.is_authenticated:
        user = request.user
        try:
            curr_student = Student.objects.get(id=user.id)
            if (curr_student):
                course_ordered = Order.objects.filter(student=curr_student)
                topic_interested = curr_student.interested_in.all()
                if request.method == 'POST':
                    form = ImageForm(request.POST, request.FILES)
                    if form.is_valid():
                        form.save()
                        img_obj = form.instance
                        return render(request, 'myapp/myaccount.html',
                                      {'student': curr_student, 'orders': course_ordered, 'topics': topic_interested,
                                       'form': form, 'img_obj': img_obj})
                else:
                    form = ImageForm()
                return render(request, 'myapp/myaccount.html',
                              {'student': curr_student, 'orders': course_ordered, 'topics': topic_interested,
                               'form': form})
            else:
                return render(request, 'myapp/myaccount.html')
        except ObjectDoesNotExist:
            return render(request, 'myapp/myaccount.html')
    else:
        return HttpResponseRedirect(reverse(('myapp:login')))


def myorders(request):
    if (request.user.is_authenticated):
        user = request.user
        try:
            curr_student = Student.objects.get(id=user.id)
            if (curr_student):
                course_ordered = Order.objects.filter(student=curr_student)
                return render(request, 'myapp/myorders.html', {'student': curr_student, 'orders': course_ordered})
            else:
                return render(request, 'myapp/myorders.html')

        except ObjectDoesNotExist:
            return render(request, 'myapp/myorders.html')
    else:
        return HttpResponseRedirect(reverse(('myapp:login')))


def password_reset(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            curr_student = Student.objects.get(username=username)
            email = curr_student.email
            passwordString = ''.join(
                random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(16))
            passwordEncrypted = hashers.make_password(passwordString)
            curr_student.password = passwordEncrypted;
            curr_student.save();
            message = "Your password has been changed successfully. Please find your new password: " + passwordString
            send_mail('Password changed successfully',
                      message,
                      settings.EMAIL_HOST_USER,
                      [email],
                      fail_silently=False)
            return render(request, 'myapp/password_reset.html', {'email': email})
    else:
        form = PasswordResetForm()
    return render(request, 'myapp/password_reset.html')


def register(request):
    if request.method == 'POST':
        form = StudentRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            school = form.cleaned_data['school']
            city = form.cleaned_data['city']
            interested_in = form.cleaned_data['interested_in']

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <strong class="m-3 lead fw-bold">This is an E-learning Website! Search our Topics to find all available Courses.</strong>
    <p class="m-3"><strong>Number of times visited (count):</strong>
        <span class="text-muted">{{ count }}</span>
    </p>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
 <meta charset="UTF-8">
 <title>E-Learning WebApp!</title>
</head>
<body>

 <strong>This is an E-learning Website! Search our Topics to find all available Courses.</strong>

 <p><a href="/myapp/">Home page static</a></p>
<p><a href="{% url "myapp:index" %}">Home page</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
        <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div class="">
            {% if request.user.is_authenticated %}
                <h2 class=" fw-bold m-3">{% block myhdg %}Hello {{ request.user.first_name }} {% endblock %}</h2>
            {% endif %}
            {% block body_block %}*** {% endblock %}
        </div><hr />
        <div>
            {% if request.user.is_authenticated %}
                <ul>
                    <li class="hbar1"><a href="/myapp/about">Find out about our E-Learning site</a></li>
                    <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:courses' %}">Click here to view List of Courses</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:myorders' %}">Click here to view List of Your Orders</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a><br/></li>
                </ul>
            {% else %}
                 <ul>
                    <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a><br/></li>
                </ul>
            {% endif %}
        </div>
    </body>
</html>

myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if course %}
        <h4 class="lead fw-bold m-3 mt-2"> Course Details: </h4>
        <div class="mx-2">&nbsp; &nbsp;<span>Name - {{ course.name }} </span> </div>
        <div class="mx-2">&nbsp; &nbsp;<span>Number of people interested - {{ course.interested }}</span> </div>
        <div class="mx-2">&nbsp; &nbsp;<span>Price - {{ course.price }} </span> </div>
        {% if course.for_everyone %}
            &nbsp; &nbsp;<strong class="mx-2">This course is for everyone</strong>
        {% else %}
            &nbsp; &nbsp;<strong class="mx-2">This course is not for everyone</strong>
        {% endif %}
        {% else %}
        <strong class="mx-2"> NO COURSE! </strong>
    {%  endif %}
    <br>
    <br>
    <h3 class="lead fw-bold mx-3 mb-0">Interested?</h3>
    <div class="form-signin w-100 mx-2">
        <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-block mb-4">
        </form>
    </div>
{% endblock %}

myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h4 class="mx-3 fw-bold lead">Courses Available</h4>

    {% if courlist %}
        <div class="mx-4 mt-2">
        {% for co in courlist %}
            <li> <a href="{% url "myapp:coursedetail" co.id %}">{{ co.name }} : {{ co.topic.name }} </a></li>
        {% endfor %}
        </div>
        <br>
        <div class="mx-2">
            <span class="mx-2 fw-bold">Want to place an order?</span>
            <li class="hbar1"><a href="{% url 'myapp:place_order' %}">Place a new order</a></li>
        </div>
    {% endif %}


{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h4 class="fw-bold m-3">Topic Details</h4>
{% if topic %}
    <div class="mx-3"><b>Topic Name:</b> {{ topic.name }}
    </div>
    <div class="mx-3">
        <b>Topic Category:</b> {{ topic.category }}
    </div>

        <b class="m-3">Related courses:</b> <br>
        <ul>
            {% for course in topic.courses.all %}
                <li class="mx-2">{{ course.name }}</li>
                {% empty %}
                    No related courses
            {% endfor %}
        </ul>
    {% else %}
        No course found!!
    {% endif %}

{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
<h1>Details</h1>
{% if topic %}
<b>Name:</b> {{ topic.name }}
<br>
<b>Categoty:</b> {{ topic.category }} <br/>

    <b>Related courses:</b> <br>
    <ul>
        {% for course in topic.courses.all %}
            <li>{{ course.name }}</li>
            <br>
            {% empty %}
                No related courses
        {% endfor %}
    </ul>
{% else %}
    No course found!!
{% endif %}

<p><a href="{% url "myapp:index" %}">Home page</a></p>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if top_list %}
 <h2 class="m-3">List of Topics Available</h2>
 <ol>
 {% for top in top_list %}
 <li><a href="{% url "myapp:detail" top.id %}" class="link-primary"> {{ top.name}} </a></li>
 {% endfor %}
 </ol>
 {% else %}
 <strong>There are no available topics!</strong>
 {% endif %}
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if student %}
        <div class="lead">&nbsp; &nbsp;<span>First Name - {{ student.first_name }} </span>
            <span>, &nbsp; &nbsp;Last Name - {{ student.last_name }} </span>
        </div>
        {% if orders %}
            <br>
            <h2 class="m-3">Courses Ordered</h2>
            {% for order in orders %}
                <div class="lead">&nbsp; &nbsp;<span>Name - {{ order.course.name }} </span>
                    <span>,&nbsp; &nbsp;Price - {{ order.course.price }} </span>
                </div>
                <br>
            {% endfor %}
        {% endif %}

        {% if topics %}
            <h2 class="m-3"> Interested Topics</h2>
            {% for topic in topics %}
                <div class="lead">&nbsp; &nbsp;<span>Name - {{ topic.name }} </span>
                    <span>,&nbsp; &nbsp;Category - {{ topic.category }} </span>
                </div>
                <br>
            {% endfor %}
        {% endif %}
        <h2 class="m-3">Upload Image</h2>
        <div class="form-signin w-100">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    {{ form.as_p }}
                <button type="submit" class="btn btn-secondary btn-block mb-4">Upload</button>
            </form>
        </div>
        {% if img_obj %}
            <h3 class="m-3">Successfully uploaded : {{img_obj.title}}</h3>
            <img class="mx-3" src="{{ img_obj.image.url}}" alt="connect" style="max-height:200px">
        {% endif %}
    {% else %}
        <strong> You are not a registered student!!</strong>
    {% endif %}

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <strong class="mx-3 fw-bold lead">{{ msg }}</strong>


{% endblock %}

myapp/templates/myapp/password_reset.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title> Login! </title>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </head>
    <body class="text-center mt-5">
        <main class="form-signin w-100 m-auto">
            <form action="/myapp/password_reset" method="post">
                {% csrf_token %}
                <div class="form-outline mb-4">
                    {% if email %}
                        <span class="lead">Your new password is sent to your email - {{ email }} </span><br><br>
                        <span class="lead">If you haven't received the email, check your spam folder</span><br><br>
                        <a class="lead" href="{% url "myapp:login" %}"> Login</a>
                    {% else %}
                        <label class="form-label" for="username">Username</label>
                        <input type="text" placeholder="Enter Username" name="username" class="form-control" required>
                        <input type="submit" value="Submit" class="btn btn-primary btn-block mt-3">
                    {% endif %}
                </div>
            </form>
        </main>
    </body>
</html>

myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <strong>This is Place Order Page.</strong>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}

    {% if courlist %}
    <table class="table mx-3">
            <thead>
                <tr>
                  <th scope="col">Course</th>
                  <th scope="col">Price</th>
                </tr>
          </thead>
      <tbody>
        {% for co in courlist %}
        <tr>
            <td>{{ co.name }}</td>
            <td>{{ co.price }}</td>
        </tr>
      </tbody>
        {% endfor %}
    </table>
    {% endif %}

    {% if form %}
        <div class="mx-3">
            <h3 class="fw-bold lead">Place New Order</h3>
            <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Place Order" class="btn btn-primary btn-block mx-2 p-1 px-2">
            </form>
        </div>
    {% endif %}

{% endblock %}

myapp/templates/myapp/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>

<body>
<div class=""> {{ msg }}</div>

    <body class="text-center mt-5">
        <main class="form-signin w-100 m-auto">
            {% if form %}
                <h3 class="p-2">Register as a student</h3>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Submit" class="btn btn-primary btn-block mb-4" />
                </form>
            {% else %}
                <a class="lead" href="{% url "myapp:login" %}"> Login</a>
            {% endif %}
        </main>
    </body>
</html>